sections:
  main:
    display: Main
    fields:
      product_category:
        type: text
        display: Category
        validate: required
      pcs_number:
        type: text
        display: pieces
        default: '6'
      price_tag:
        type: text
        instructions: 'Her skal du skrive prisen på produktet.'
        display: Price
        validate: required
      title_of_description:
        type: text
        display: 'Title of description'
        validate: required
      description:
        type: textarea
        display: Description
        validate: required
      product_picture:
        container: main
        folder: /
        restrict: false
        max_files: 1
        mode: grid
        type: assets
        display: Picture
        validate: required
      add_parallax_to_singleproduct:
        type: toggle
        width: 50
        display: 'Add parallax'
      image_scroll_speed_singleproduct:
        type: text
        width: 50
        display: 'Image scroll speed'
        default: '-1.5'
  sidebar:
    display: Sidebar
    fields:
      background_color:
        options:
          '#FFBDC6': Pink
          '#FAEFE5': Peach
          '#DFEDFB': 'Baby blue'
        type: select
        display: 'Background color'
        default: Pink
      field_2:
        type: toggle
        display: 'Field 2'
  naeringsinhold:
    display: Næringsindhold
    fields:
      nutrient_energi:
        type: text
        display: Energi
        validate: required
        default: '0'
      nutrient_fedt:
        type: text
        display: Fedt
        validate: required
        default: '0'
      nutrient_fedtsyrer:
        type: text
        display: 'Mættede fedtsyrer'
        validate: required
        default: '0'
      nutrient_kulhydrat:
        type: text
        display: Kulhydrat
        validate: required
        default: '0'
      nutrient_sukkerarter:
        type: text
        display: Sukkerarter
        validate: required
        default: '0'
      nutrient_protein:
        type: text
        display: Protein
        validate: required
        default: '0'
      nutrient_salt:
        type: text
        display: Salt
        validate: required
        default: '0'
  ingredienser:
    display: Ingredienser
    fields:
      ingredients:
        sets:
          ingrediens:
            display: ingrediens
            fields:
              ingredient_name:
                type: text
                display: Name
              ingredient_image:
                container: main
                folder: /
                restrict: false
                max_files: 1
                type: assets
                display: Image
        type: replicator
        display: Ingredienser
  inspirations_billeder:
    display: 'Inspirations billeder'
    fields:
      inspi_img_big:
        container: main
        folder: /
        restrict: false
        max_files: 1
        type: assets
        display: 'Inspirations billede - Stor'
        width: 50
      inspi_img_small:
        container: main
        folder: /
        restrict: false
        max_files: 1
        type: assets
        display: 'Inspirations billede - Lille'
        width: 50
      add_parallax_to_inspi:
        type: toggle
        width: 33
        display: 'Add parallax to images'
        default: 'true'
      image_scroll_speed_small_singleproduct:
        type: text
        width: 33
        display: 'Image speed scroll - Small'
        default: '0.3'
taxonomies: true
title: 'c: Product'
